//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCommService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private DBCommService.UserCredentials credsField;
        
        private int idField;
        
        private bool is_bannedField;
        
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DBCommService.UserCredentials creds {
            get {
                return this.credsField;
            }
            set {
                if ((object.ReferenceEquals(this.credsField, value) != true)) {
                    this.credsField = value;
                    this.RaisePropertyChanged("creds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool is_banned {
            get {
                return this.is_bannedField;
            }
            set {
                if ((this.is_bannedField.Equals(value) != true)) {
                    this.is_bannedField = value;
                    this.RaisePropertyChanged("is_banned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCredentials", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UserCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string emailField;
        
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Character", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Character : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<DBCommService.Quest> QuestsField;
        
        private System.Nullable<int> bladderField;
        
        private int dayField;
        
        private System.Nullable<int> energyField;
        
        private System.Nullable<int> funField;
        
        private int global_scoreField;
        
        private int gradesField;
        
        private int hourField;
        
        private System.Nullable<int> hungerField;
        
        private int idField;
        
        private int minuteField;
        
        private System.Nullable<int> moneyField;
        
        private string nameField;
        
        private string positionField;
        
        private System.Nullable<int> sanityField;
        
        private string sexField;
        
        private int weekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<DBCommService.Quest> Quests {
            get {
                return this.QuestsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestsField, value) != true)) {
                    this.QuestsField = value;
                    this.RaisePropertyChanged("Quests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> bladder {
            get {
                return this.bladderField;
            }
            set {
                if ((this.bladderField.Equals(value) != true)) {
                    this.bladderField = value;
                    this.RaisePropertyChanged("bladder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int day {
            get {
                return this.dayField;
            }
            set {
                if ((this.dayField.Equals(value) != true)) {
                    this.dayField = value;
                    this.RaisePropertyChanged("day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> energy {
            get {
                return this.energyField;
            }
            set {
                if ((this.energyField.Equals(value) != true)) {
                    this.energyField = value;
                    this.RaisePropertyChanged("energy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> fun {
            get {
                return this.funField;
            }
            set {
                if ((this.funField.Equals(value) != true)) {
                    this.funField = value;
                    this.RaisePropertyChanged("fun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int global_score {
            get {
                return this.global_scoreField;
            }
            set {
                if ((this.global_scoreField.Equals(value) != true)) {
                    this.global_scoreField = value;
                    this.RaisePropertyChanged("global_score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int grades {
            get {
                return this.gradesField;
            }
            set {
                if ((this.gradesField.Equals(value) != true)) {
                    this.gradesField = value;
                    this.RaisePropertyChanged("grades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int hour {
            get {
                return this.hourField;
            }
            set {
                if ((this.hourField.Equals(value) != true)) {
                    this.hourField = value;
                    this.RaisePropertyChanged("hour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> hunger {
            get {
                return this.hungerField;
            }
            set {
                if ((this.hungerField.Equals(value) != true)) {
                    this.hungerField = value;
                    this.RaisePropertyChanged("hunger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int minute {
            get {
                return this.minuteField;
            }
            set {
                if ((this.minuteField.Equals(value) != true)) {
                    this.minuteField = value;
                    this.RaisePropertyChanged("minute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> money {
            get {
                return this.moneyField;
            }
            set {
                if ((this.moneyField.Equals(value) != true)) {
                    this.moneyField = value;
                    this.RaisePropertyChanged("money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> sanity {
            get {
                return this.sanityField;
            }
            set {
                if ((this.sanityField.Equals(value) != true)) {
                    this.sanityField = value;
                    this.RaisePropertyChanged("sanity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                if ((object.ReferenceEquals(this.sexField, value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int week {
            get {
                return this.weekField;
            }
            set {
                if ((this.weekField.Equals(value) != true)) {
                    this.weekField = value;
                    this.RaisePropertyChanged("week");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quest", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Quest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<DBCommService.QuestNode> NodesField;
        
        private int current_nodeField;
        
        private int day_assignedField;
        
        private string descriptionField;
        
        private int idField;
        
        private int num_nodesField;
        
        private int week_assignedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<DBCommService.QuestNode> Nodes {
            get {
                return this.NodesField;
            }
            set {
                if ((object.ReferenceEquals(this.NodesField, value) != true)) {
                    this.NodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int current_node {
            get {
                return this.current_nodeField;
            }
            set {
                if ((this.current_nodeField.Equals(value) != true)) {
                    this.current_nodeField = value;
                    this.RaisePropertyChanged("current_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int day_assigned {
            get {
                return this.day_assignedField;
            }
            set {
                if ((this.day_assignedField.Equals(value) != true)) {
                    this.day_assignedField = value;
                    this.RaisePropertyChanged("day_assigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int num_nodes {
            get {
                return this.num_nodesField;
            }
            set {
                if ((this.num_nodesField.Equals(value) != true)) {
                    this.num_nodesField = value;
                    this.RaisePropertyChanged("num_nodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int week_assigned {
            get {
                return this.week_assignedField;
            }
            set {
                if ((this.week_assignedField.Equals(value) != true)) {
                    this.week_assignedField = value;
                    this.RaisePropertyChanged("week_assigned");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestNode", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class QuestNode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InteractiveObjectField;
        
        private string NodeLocationField;
        
        private DBCommService.QuestNodeType NodeTypeField;
        
        private int NodeValueField;
        
        private DBCommService.QuestEmail QuestDescriptionField;
        
        private int accumulated_valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InteractiveObject {
            get {
                return this.InteractiveObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.InteractiveObjectField, value) != true)) {
                    this.InteractiveObjectField = value;
                    this.RaisePropertyChanged("InteractiveObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NodeLocation {
            get {
                return this.NodeLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeLocationField, value) != true)) {
                    this.NodeLocationField = value;
                    this.RaisePropertyChanged("NodeLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DBCommService.QuestNodeType NodeType {
            get {
                return this.NodeTypeField;
            }
            set {
                if ((this.NodeTypeField.Equals(value) != true)) {
                    this.NodeTypeField = value;
                    this.RaisePropertyChanged("NodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NodeValue {
            get {
                return this.NodeValueField;
            }
            set {
                if ((this.NodeValueField.Equals(value) != true)) {
                    this.NodeValueField = value;
                    this.RaisePropertyChanged("NodeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DBCommService.QuestEmail QuestDescription {
            get {
                return this.QuestDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestDescriptionField, value) != true)) {
                    this.QuestDescriptionField = value;
                    this.RaisePropertyChanged("QuestDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int accumulated_value {
            get {
                return this.accumulated_valueField;
            }
            set {
                if ((this.accumulated_valueField.Equals(value) != true)) {
                    this.accumulated_valueField = value;
                    this.RaisePropertyChanged("accumulated_value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestEmail", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class QuestEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<string> BodyField;
        
        private string SenderField;
        
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<string> Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestNodeType", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    public enum QuestNodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Goto = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Money = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sanity = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bladder = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Energy = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Use = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MinigameScore", Namespace="http://schemas.datacontract.org/2004/07/DBCommService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class MinigameScore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CharacterIDField;
        
        private string CharacterNameField;
        
        private bool Lecture_AttendedField;
        
        private int MinigameIDField;
        
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CharacterID {
            get {
                return this.CharacterIDField;
            }
            set {
                if ((this.CharacterIDField.Equals(value) != true)) {
                    this.CharacterIDField = value;
                    this.RaisePropertyChanged("CharacterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CharacterName {
            get {
                return this.CharacterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CharacterNameField, value) != true)) {
                    this.CharacterNameField = value;
                    this.RaisePropertyChanged("CharacterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Lecture_Attended {
            get {
                return this.Lecture_AttendedField;
            }
            set {
                if ((this.Lecture_AttendedField.Equals(value) != true)) {
                    this.Lecture_AttendedField = value;
                    this.RaisePropertyChanged("Lecture_Attended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MinigameID {
            get {
                return this.MinigameIDField;
            }
            set {
                if ((this.MinigameIDField.Equals(value) != true)) {
                    this.MinigameIDField = value;
                    this.RaisePropertyChanged("MinigameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBCommService.IDBCommService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDBCommService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/GetUserDetails", ReplyAction="http://tempuri.org/IDBCommService/GetUserDetailsResponse")]
        DBCommService.User GetUserDetails(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/SendPasswordResetEmail", ReplyAction="http://tempuri.org/IDBCommService/SendPasswordResetEmailResponse")]
        bool SendPasswordResetEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/LoadCharacterData", ReplyAction="http://tempuri.org/IDBCommService/LoadCharacterDataResponse")]
        DBCommService.Character LoadCharacterData(DBCommService.User theUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/SaveNewCharacterData", ReplyAction="http://tempuri.org/IDBCommService/SaveNewCharacterDataResponse")]
        bool SaveNewCharacterData(DBCommService.Character newCharacterData, DBCommService.User theUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/SaveExistingCharacterData", ReplyAction="http://tempuri.org/IDBCommService/SaveExistingCharacterDataResponse")]
        bool SaveExistingCharacterData(DBCommService.Character characterData, DBCommService.User theUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/SaveMinigameScore", ReplyAction="http://tempuri.org/IDBCommService/SaveMinigameScoreResponse")]
        bool SaveMinigameScore(DBCommService.User userData, DBCommService.MinigameScore minigameScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/GetMinigameHighScores", ReplyAction="http://tempuri.org/IDBCommService/GetMinigameHighScoresResponse")]
        System.Collections.Generic.List<DBCommService.MinigameScore> GetMinigameHighScores(DBCommService.User userData, int minigameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/LoadQuestData", ReplyAction="http://tempuri.org/IDBCommService/LoadQuestDataResponse")]
        System.Collections.Generic.List<DBCommService.Quest> LoadQuestData(DBCommService.User userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/SaveQuestAssociation", ReplyAction="http://tempuri.org/IDBCommService/SaveQuestAssociationResponse")]
        bool SaveQuestAssociation(DBCommService.User userData, DBCommService.Character characterData, DBCommService.Quest theQuest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/UpdateQuestAssociation", ReplyAction="http://tempuri.org/IDBCommService/UpdateQuestAssociationResponse")]
        bool UpdateQuestAssociation(DBCommService.User userData, DBCommService.Character characterData, DBCommService.Quest theQuest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/GetLectureAttended", ReplyAction="http://tempuri.org/IDBCommService/GetLectureAttendedResponse")]
        bool GetLectureAttended(DBCommService.User userData, DBCommService.Character characterData, int minigameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/SetLectureAttended", ReplyAction="http://tempuri.org/IDBCommService/SetLectureAttendedResponse")]
        bool SetLectureAttended(DBCommService.User userData, DBCommService.Character characterData, int minigameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBCommService/DeleteCharacter", ReplyAction="http://tempuri.org/IDBCommService/DeleteCharacterResponse")]
        bool DeleteCharacter(DBCommService.User userData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBCommServiceChannel : DBCommService.IDBCommService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBCommServiceClient : System.ServiceModel.ClientBase<DBCommService.IDBCommService>, DBCommService.IDBCommService {
        
        public DBCommServiceClient() {
        }
        
        public DBCommServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBCommServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBCommServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBCommServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DBCommService.User GetUserDetails(string email, string password) {
            return base.Channel.GetUserDetails(email, password);
        }
        
        public bool SendPasswordResetEmail(string email) {
            return base.Channel.SendPasswordResetEmail(email);
        }
        
        public DBCommService.Character LoadCharacterData(DBCommService.User theUser) {
            return base.Channel.LoadCharacterData(theUser);
        }
        
        public bool SaveNewCharacterData(DBCommService.Character newCharacterData, DBCommService.User theUser) {
            return base.Channel.SaveNewCharacterData(newCharacterData, theUser);
        }
        
        public bool SaveExistingCharacterData(DBCommService.Character characterData, DBCommService.User theUser) {
            return base.Channel.SaveExistingCharacterData(characterData, theUser);
        }
        
        public bool SaveMinigameScore(DBCommService.User userData, DBCommService.MinigameScore minigameScore) {
            return base.Channel.SaveMinigameScore(userData, minigameScore);
        }
        
        public System.Collections.Generic.List<DBCommService.MinigameScore> GetMinigameHighScores(DBCommService.User userData, int minigameID) {
            return base.Channel.GetMinigameHighScores(userData, minigameID);
        }
        
        public System.Collections.Generic.List<DBCommService.Quest> LoadQuestData(DBCommService.User userData) {
            return base.Channel.LoadQuestData(userData);
        }
        
        public bool SaveQuestAssociation(DBCommService.User userData, DBCommService.Character characterData, DBCommService.Quest theQuest) {
            return base.Channel.SaveQuestAssociation(userData, characterData, theQuest);
        }
        
        public bool UpdateQuestAssociation(DBCommService.User userData, DBCommService.Character characterData, DBCommService.Quest theQuest) {
            return base.Channel.UpdateQuestAssociation(userData, characterData, theQuest);
        }
        
        public bool GetLectureAttended(DBCommService.User userData, DBCommService.Character characterData, int minigameID) {
            return base.Channel.GetLectureAttended(userData, characterData, minigameID);
        }
        
        public bool SetLectureAttended(DBCommService.User userData, DBCommService.Character characterData, int minigameID) {
            return base.Channel.SetLectureAttended(userData, characterData, minigameID);
        }
        
        public bool DeleteCharacter(DBCommService.User userData) {
            return base.Channel.DeleteCharacter(userData);
        }
    }
}
